apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
  labels:
    app: ml-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app
        image: 369886907351.dkr.ecr.us-east-1.amazonaws.com/ola-demo:replaceImageTag
        ports:
        - containerPort: 8080