apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
  selector:
    app: ml-app